### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by meinhard-meintjes** [tonioseiler/craft-commerce-wallee#1]
Hi guys

Regarding version 2.2.0 running on Craft v4.4.14 and Commerce v4.2.11:

When using the "_iframe_" setting we're currently getting the script error "_xxx:1377 Uncaught TypeError: Cannot read properties of null (reading 'style')" after clicking on one of our payment option buttons.

It seems like it's just old class/id names that need to be updated in the javascript part of your code (_iframe.html:21):
```
var handler, 
        elements = document.getElementsByClassName("wallee-pay"), 
        buttonPay = document.getElementById('wallee-pay'),
        loading = document.getElementById('wallee-rest-form-loading');
```

Kind regards
Meinhard

**Comment by tonioseiler** [comment]
We try to solve this tomorrow…

–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by tonioseiler** [comment]
Hi Meinhard,

We did a test and everything works fine for us. We tried to fix the line but we could not test. Can you send us a link to your installation?

Regards

Tonio

–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by meinhard-meintjes** [comment]
Hi Tonio

I've sent you an email with the link to our staging page.
You'll have to add something to the cart and go all the way to checkout, then choose "Kreditkarte / PayPal / Twint".
									
```
payment:1391 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
payment:1369 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at HTMLDivElement.<anonymous> (payment:1369:63)
```
And that points to the code below:
```
document.getElementById('payment-form').innerHTML = '';
```
Unfortunately there is no element with the ID "payment-form", only "paymentForm-wallee-payment-form".
I hope that helps.

PS: Apart from that everything is working fine now, in production, and people are using Twint the majority of the time :)

Kind regards
Meinhard

**Comment by tonioseiler** [comment]
marked resolved
