### ISSUE TITLE
Craft 5

### ISSUE THREAD

**Issue by alexanderloewe** [tonioseiler/craft-commerce-wallee#2]
Hello together

are there plans to continue this plugin for Craft CMS 5?

**Comment by tonioseiler** [comment]
Yes,

We will will do this in the next 2 Months.

Regards


–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by tonioseiler** [comment]
We have this version ready now!

**Comment by alexanderloewe** [comment]
Thanks
