### ISSUE TITLE
Order Status not updated by webhook

### ISSUE THREAD

**Issue by frederik-station** [tonioseiler/craft-commerce-wallee#4]
Craft: 4.11.5
Craft Commerce: 4.6.10
Wallee: 2.3.12

After completing an order via the payment form, the order status in Craft is not updated by the Wallee webhook but remains in my default "New" state.

Here is my mapping of Wallee Payment States to Craft Order States:
<img width="335" alt="image" src="https://github.com/user-attachments/assets/ceccb3e4-1a8d-481f-852f-356fe78f7869">

The webhook invocation shows up as "successful" in Wallee and I see some logs regarding the order status change:

```
2024-09-13 17:11:14 [web.INFO] [craft-commerce-wallee] Wallee state: FULFILL
2024-09-13@17:11:14
staging
php
stderr
2024-09-13 17:11:14 [web.INFO] [craft-commerce-wallee] change order status: 5-2
2024-09-13@17:11:14
staging
php
stderr
```

When I manually trigger a resend of the webhook invocation via the Wallee Backend, the order status is correctly updated in Craft.

**Comment by tonioseiler** [comment]
Hi Frederick,

We will look at this asap.
Are the log file triggered by the transaction or when you fire it manually?
What is order state 2 in your case? the orders shoudl be changed to this state according to your logs.

**Comment by frederik-station** [comment]
Thx Tonio!

The logs were triggered by the transaction.

Here are my order state IDs:
<img width="138" alt="image" src="https://github.com/user-attachments/assets/f4544138-7d05-4993-8f40-ce58bc5cf2f6">

**Comment by tonioseiler** [comment]
@frederik-station The bug shluld be resolved in the latest version of the plugin....

**Comment by station-ag** [comment]
@tonioseiler sorry for the late reply. The fix seems to have broken sth. After simulating the payment no order is created and the line items remain in the cart.

**Comment by cmartinespinosa** [comment]
Hi @station-ag , apologies for the delayed response. Could you please send me the versions of Craft CMS, Craft Commerce, and the Commerce Wallee Gateway Plugin?

Also, could you confirm if your webhook listener matches this example:
 
<img width="1047" alt="Screenshot 2024-12-05 at 11 57 22" src="https://github.com/user-attachments/assets/7e49fb9d-f38b-4705-9b1b-8e0d036dffd6">

And in the plugins settings in Craft:

<img width="621" alt="image" src="https://github.com/user-attachments/assets/4ec76824-ac1b-4949-b97b-3c40a6117e59">



 
 Thanks

**Comment by frederik-station** [comment]
Thank you @cmartinespinosa, I tested it again with the 2.3.12 version and it was working. Maybe I had forgotten to turn off basic auth on our staging environment when I reported the issue.

**Comment by frederik-station** [comment]
Update: Not working for Craft 5

I'm currently in the process of upgrading to Craft 5 and I tested with the following versions:
Craft: 5.5.6.1
Craft Commerce: 5.2.9
Wallee: 5.0.5
