### ISSUE TITLE
Cannot redeclare processWebHook error in 5.0.6 and 5.0.7

### ISSUE THREAD

**Issue by maikueo** [tonioseiler/craft-commerce-wallee#6]
Hey there 👋 
Upgrading to 5.0.6 or 5.0.7 gives a Cannot redeclare processWebHook error

See lines 210 and 291 in Gateway.php

**Comment by cmartinespinosa** [comment]
Hi @maikueo! Thanks for the feedback! We have already addressed it in the latest release (5.0.8).
